//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.courses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Course_Members = new HashSet<Course_Members>();
            this.Room_Members = new HashSet<Room_Members>();
            this.Work_group_members = new HashSet<Work_group_members>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public string Apout { get; set; }
        public string AnotherAccount { get; set; }
        public Nullable<bool> IsInstructor { get; set; }
        public string GuaranteeDecument { get; set; }
        public string IdCard { get; set; }
        public string Residence { get; set; }
        public string Photograph { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Course_Members> Course_Members { get; set; }
        public virtual ICollection<Room_Members> Room_Members { get; set; }
        public virtual ICollection<Work_group_members> Work_group_members { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
